shim-version: v0.3.16@sha256:20220be4487f241e7e2a9af6dd576d20ba35d71307bd777c8dba9ba5da03fb38
cvm-version: 0.6.7
cpus: 2
memory: 8192

containers:
  - name: "app"
    image: "image: ghcr.io/lsd-cat/docker-reverse-ssh/reverse-ssh@sha256:408c87305f4713c9aaf530640fff03415db5760f9f71dc0d55407d53ff243c59"
    env:
      - APP_NAME=tinfoil-test-app
      - LOG_LEVEL=debug

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
